# Generated by Django 4.2.29 on 2026-04-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_photo_url_ministry_image_url_and_more'),
        ('events', '0002_event_image_url_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ministry',
            field=models.ForeignKey(blank=True, help_text='Ministry organizing this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='members.ministry'),
        ),
    ]
