# Generated by Django 4.2.29 on 2026-03-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryalbum_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='title',
            field=models.CharField(blank=True, help_text='Optional: Leave blank to auto-generate', max_length=200),
        ),
    ]
