# Generated by Django 4.2.29 on 2026-03-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Or provide photo URL', null=True),
        ),
        migrations.AddField(
            model_name='ministry',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide image URL', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload member photo', null=True, upload_to='members/'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload ministry image', null=True, upload_to='ministries/'),
        ),
    ]
