# Generated by Django 4.2.29 on 2026-03-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('head', 'Head Pastor'), ('associate', 'Associate Pastor'), ('youth', 'Youth Pastor'), ('worship', 'Worship Pastor')], max_length=20)),
                ('bio', models.TextField()),
                ('photo', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('joined_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='churchinfo',
            options={'ordering': ['-id'], 'verbose_name': 'Church Information', 'verbose_name_plural': 'Church Information'},
        ),
    ]
