# Generated by Django 4.2.29 on 2026-03-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_corevalue_servicetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchinfo',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Or provide logo URL', null=True),
        ),
        migrations.AddField(
            model_name='pastor',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Or provide photo URL', null=True),
        ),
        migrations.AlterField(
            model_name='churchinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload church logo', null=True, upload_to='church/'),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload pastor photo', null=True, upload_to='pastors/'),
        ),
    ]
