# Generated by Django 4.2.29 on 2026-03-18 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_pastor_alter_churchinfo_options'),
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='pastor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='church.pastor'),
        ),
        migrations.DeleteModel(
            name='Pastor',
        ),
    ]
