# Generated by Django 4.2.29 on 2026-03-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_alter_sermon_pastor_delete_pastor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Third Sunday in Lent'", max_length=200)),
                ('service_date', models.DateField(help_text='Date of the service')),
                ('is_active', models.BooleanField(default=True, help_text="Set to True for current week's bulletin")),
                ('has_communion', models.BooleanField(default=False, help_text='Check if communion will be served')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or announcements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weekly Bulletin',
                'verbose_name_plural': 'Weekly Bulletins',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hymn_type', models.CharField(choices=[('opening', 'Opening Hymn'), ('communion', 'Communion Hymn'), ('closing', 'Closing Hymn'), ('recessional', 'Recessional Hymn')], max_length=20)),
                ('hymn_number', models.CharField(blank=True, help_text='Hymn number from hymnal', max_length=50)),
                ('hymn_title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hymns', to='sermons.weeklybulletin')),
            ],
            options={
                'verbose_name': 'Service Hymn',
                'verbose_name_plural': 'Service Hymns',
                'ordering': ['order', 'hymn_type'],
            },
        ),
        migrations.CreateModel(
            name='BibleReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('first', '1st Reading'), ('second', '2nd Reading'), ('gospel', '3rd Reading (Gospel)'), ('akan', 'Akan Reading'), ('fante', 'Fante Reading')], max_length=20)),
                ('reader_name', models.CharField(max_length=200)),
                ('reader_photo', models.URLField(blank=True, help_text="URL to reader's photo", null=True)),
                ('scripture_reference', models.CharField(help_text="e.g., 'Genesis 1:1-2'", max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sermons.weeklybulletin')),
            ],
            options={
                'verbose_name': 'Bible Reading',
                'verbose_name_plural': 'Bible Readings',
                'ordering': ['order', 'reading_type'],
            },
        ),
    ]
