# Generated by Django 4.2.29 on 2026-03-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0003_weeklybulletin_servicehymn_biblereading'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblereading',
            name='reader_photo_url',
            field=models.URLField(blank=True, help_text='Or provide photo URL', null=True),
        ),
        migrations.AddField(
            model_name='servicehymn',
            name='custom_hymn_type',
            field=models.CharField(blank=True, help_text="Custom hymn type (if 'Other' is selected)", max_length=100),
        ),
        migrations.AlterField(
            model_name='biblereading',
            name='reader_photo',
            field=models.ImageField(blank=True, help_text="Upload reader's photo", null=True, upload_to='readers/'),
        ),
        migrations.AlterField(
            model_name='servicehymn',
            name='hymn_type',
            field=models.CharField(choices=[('opening', 'Opening Hymn'), ('communion', 'Communion Hymn'), ('closing', 'Closing Hymn'), ('recessional', 'Recessional Hymn'), ('other', 'Other')], max_length=20),
        ),
    ]
