# Generated by Django 4.2.29 on 2026-03-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0004_biblereading_reader_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblereading',
            name='reading_type',
            field=models.CharField(choices=[('first', '1st Reading'), ('second', '2nd Reading'), ('gospel', '3rd Reading (Gospel)'), ('akan', 'Akan Reading'), ('fante', 'Fante Reading'), ('ga', 'Ga Reading')], max_length=20),
        ),
    ]
