# Generated by Django 4.2.29 on 2026-03-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0005_alter_biblereading_reading_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Or provide thumbnail URL', null=True),
        ),
        migrations.AddField(
            model_name='sermonseries',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide image URL', null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload sermon thumbnail', null=True, upload_to='sermon_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='sermonseries',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload series image', null=True, upload_to='sermon_series/'),
        ),
    ]
