# Generated by Django 4.2.29 on 2026-03-19 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_churchinfo_logo_url_pastor_photo_url_and_more'),
        ('sermons', '0006_sermon_thumbnail_url_sermonseries_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklybulletin',
            name='pastor',
            field=models.ForeignKey(blank=True, help_text='Pastor preaching this week', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='church.pastor'),
        ),
    ]
