# Generated by Django 4.2.29 on 2026-03-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0007_weeklybulletin_pastor'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklybulletin',
            name='psalm_of_the_day',
            field=models.CharField(blank=True, help_text="e.g., 'Psalm 23' or 'Psalm 91:1-16'", max_length=200),
        ),
    ]
